ALTER TABLE cars ADD COLUMN IF NOT EXISTS drivetrain_id INT NOT NULL REFERENCES drivetrains(id);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel_type_id INT NOT NULL REFERENCES fuel_types(id);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS door_count_id INT NOT NULL REFERENCES doors(id);